name: avaliacao_08
description: A new Flutter application

publish_to: "none"

environment:
  sdk: "^3.8.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  provider: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
